// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gitJaesik/stream_go_srvs/stream-auth-server-go/config"
	"github.com/gitJaesik/stream_go_srvs/stream-auth-server-go/server"
	"github.com/gitJaesik/stream_go_srvs/streamgolib/db"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

// initializeConfig ...
func initializeConfig() *config.SGLConfig {
	sglConfig := config.InitializeViperConfig()
	return sglConfig
}

func initializeServer(sglConfig *config.SGLConfig, mongodb db.StreamGoLibDB) *grpc.Server {
	grpcServer := server.InitializeGrpcServer(sglConfig, mongodb)
	return grpcServer
}

func initializeGatewayMux() *runtime.ServeMux {
	serveMux := server.InitializeGatewayMux()
	return serveMux
}
