// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gitJaesik/stream_go_srvs/stream-auth-server-go/config"
)

// Injectors from wire.go:

// initializeConfig ...
func initializeConfig() *config.SGLConfig {
	sglConfig := config.InitializeViperConfig()
	return sglConfig
}
